#!/bin/bash

SECONDS=0
start=0
#echo > log.txt "$SECONDS"
[[ -e log.txt ]] || echo > log.txt "$SECONDS"

SPOILER="I watched Avengers: Endgame."

while ((1))
do
	if [[ $start != $((SECONDS/2)) ]]
	then

		
		echo "$((SECONDS/2))"
		echo >> log.txt "$((SECONDS/2))"
		start=$((SECONDS/2))
	       sleep 0.00001     #delay
		RAND=$RANDOM
		if [[ $((RAND%3)) -eq 0 ]]
		then
			echo $SPOILER
			echo >> log.txt "$SPOILER"
			continue
			
		fi
	fi	
done

